// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "LoggerC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Enum_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/AnyTypeCode/Struct_TypeCode_Static.h"
#include "tao/AnyTypeCode/TypeCode_Struct_Field.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/SystemException.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/AnyTypeCode/Any_Dual_Impl_T.h"
#include "tao/AnyTypeCode/Any_Basic_Impl_T.h"
#include "cstring"

#if !defined (__ACE_INLINE__)
#include "LoggerC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_exception/exception_cs.cpp:97

NenhumEventoCadastrado::NenhumEventoCadastrado ()
  : ::CORBA::UserException (
        "IDL:NenhumEventoCadastrado:1.0",
        "NenhumEventoCadastrado")
{
}

NenhumEventoCadastrado::NenhumEventoCadastrado (const ::NenhumEventoCadastrado &_tao_excp)
  : ::CORBA::UserException (
        _tao_excp._rep_id (),
        _tao_excp._name ())
{
}

NenhumEventoCadastrado&
NenhumEventoCadastrado::operator= (const ::NenhumEventoCadastrado &_tao_excp)
{
  this->::CORBA::UserException::operator= (_tao_excp);
  return *this;
}

void NenhumEventoCadastrado::_tao_any_destructor (void *_tao_void_pointer)
{
  NenhumEventoCadastrado *_tao_tmp_pointer =
    static_cast<NenhumEventoCadastrado *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

NenhumEventoCadastrado *
NenhumEventoCadastrado::_downcast (::CORBA::Exception *_tao_excp)
{
  return dynamic_cast<NenhumEventoCadastrado *> (_tao_excp);
}

const NenhumEventoCadastrado *
NenhumEventoCadastrado::_downcast (::CORBA::Exception const *_tao_excp)
{
  return dynamic_cast<const NenhumEventoCadastrado *> (_tao_excp);
}

::CORBA::Exception *NenhumEventoCadastrado::_alloc ()
{
  ::CORBA::Exception *retval {};
  ACE_NEW_RETURN (retval, ::NenhumEventoCadastrado, nullptr);
  return retval;
}

::CORBA::Exception *
NenhumEventoCadastrado::_tao_duplicate () const
{
  ::CORBA::Exception *result {};
  ACE_NEW_RETURN (result, ::NenhumEventoCadastrado (*this), nullptr);
  return result;
}

void NenhumEventoCadastrado::_raise () const
{
  throw *this;
}

void NenhumEventoCadastrado::_tao_encode (TAO_OutputCDR &cdr) const
{
  if (!(cdr << *this))
    {
      throw ::CORBA::MARSHAL ();
    }
}

void NenhumEventoCadastrado::_tao_decode (TAO_InputCDR &cdr)
{
  if (!(cdr >> *this))
    {
      throw ::CORBA::MARSHAL ();
    }
}

// TAO extension - the virtual _type method.
::CORBA::TypeCode_ptr NenhumEventoCadastrado::_tao_type () const
{
  return ::_tc_NenhumEventoCadastrado;
}
// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const * const 
    _tao_fields_NenhumEventoCadastrado = nullptr;
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_NenhumEventoCadastrado (
  ::CORBA::tk_except,
  "IDL:NenhumEventoCadastrado:1.0",
  "NenhumEventoCadastrado",
  _tao_fields_NenhumEventoCadastrado,
  0);

::CORBA::TypeCode_ptr const _tc_NenhumEventoCadastrado =
  &_tao_tc_NenhumEventoCadastrado;
// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_typecode/enum_typecode.cpp:27

static char const * const _tao_enumerators_Severidade[] =
  {
    "DEBUG",
    "WARNING",
    "ERROR",
    "CRITICAL"
    
  };

static TAO::TypeCode::Enum<char const *,
                           char const * const *,
                           TAO::Null_RefCount_Policy>
  _tao_tc_Severidade (
    "IDL:Severidade:1.0",
    "Severidade",
    _tao_enumerators_Severidade,
    4);
  
::CORBA::TypeCode_ptr const _tc_Severidade =
  &_tao_tc_Severidade;
// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Logger.

Logger_ptr
TAO::Objref_Traits<Logger>::duplicate (Logger_ptr p)
{
  return Logger::_duplicate (p);
}

void
TAO::Objref_Traits<Logger>::release (Logger_ptr p)
{
  ::CORBA::release (p);
}

Logger_ptr
TAO::Objref_Traits<Logger>::nil ()
{
  return Logger::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Logger>::marshal (const Logger_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

void
Logger::log (
  ::Severidade severidade,
  const std::string endereco,
  ::CORBA::Short pid,
  ::CORBA::Long hora,
  const std::string descricao)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::Severidade>::in_arg_val _tao_severidade (severidade);
  TAO::Arg_Traits< std::string>::in_arg_val _tao_endereco (endereco);
  TAO::Arg_Traits< ::CORBA::Short>::in_arg_val _tao_pid (pid);
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_hora (hora);
  TAO::Arg_Traits< std::string>::in_arg_val _tao_descricao (descricao);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_severidade),
      std::addressof(_tao_endereco),
      std::addressof(_tao_pid),
      std::addressof(_tao_hora),
      std::addressof(_tao_descricao)
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      6,
      "log",
      3,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_ONEWAY_INVOCATION
      
    );

  _invocation_call.invoke (nullptr, 0);
}
// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

std::string
Logger::locate (
  ::Severidade s)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< std::string>::ret_val _tao_retval;
  TAO::Arg_Traits< ::Severidade>::in_arg_val _tao_s (s);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_s)
    };

  static TAO::Exception_Data
  _tao_Logger_locate_exceptiondata [] = 
    {
      {
        "IDL:NenhumEventoCadastrado:1.0",
        NenhumEventoCadastrado::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , _tc_NenhumEventoCadastrado
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      2,
      "locate",
      6,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _invocation_call.invoke (
      _tao_Logger_locate_exceptiondata,
      1
    );

  return _tao_retval.retn ();
}

Logger::Logger ()
{
}
void
Logger::_tao_any_destructor (void *_tao_void_pointer)
{
  Logger *_tao_tmp_pointer =
    static_cast<Logger *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

Logger_ptr
Logger::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TAO::Narrow_Utils<Logger>::narrow (_tao_objref, "IDL:Logger:1.0");
}

Logger_ptr
Logger::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TAO::Narrow_Utils<Logger>::unchecked_narrow (_tao_objref);
}

Logger_ptr
Logger::_nil ()
{
  return nullptr;
}

Logger_ptr
Logger::_duplicate (Logger_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Logger::_tao_release (Logger_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Logger::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:Logger:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* Logger::_interface_repository_id () const
{
  return "IDL:Logger:1.0";
}

::CORBA::Boolean
Logger::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}
// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_typecode/objref_typecode.cpp:68

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_Logger (
    ::CORBA::tk_objref,
    "IDL:Logger:1.0",
    "Logger");
  
::CORBA::TypeCode_ptr const _tc_Logger =
  &_tao_tc_Logger;
// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_exception/any_op_cs.cpp:36


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Dual_Impl_T<NenhumEventoCadastrado>::demarshal_value (TAO_InputCDR & cdr)
  {
    ::CORBA::String_var id;

    if (!(cdr >> id.out ()))
      {
        return false;
      }
    
    try
      {
        this->value_->_tao_decode (cdr);
      }
    catch (const ::CORBA::Exception &)
      {
        return false;
      }

    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {



/// Copying insertion.
void operator<<= (
  ::CORBA::Any &_tao_any,
  const NenhumEventoCadastrado &_tao_elem)
{
  TAO::Any_Dual_Impl_T<NenhumEventoCadastrado>::insert_copy (
    _tao_any,
    NenhumEventoCadastrado::_tao_any_destructor,
    _tc_NenhumEventoCadastrado,
    _tao_elem);
}

/// Non-copying insertion.
void operator<<= (
  ::CORBA::Any &_tao_any,
  NenhumEventoCadastrado *_tao_elem)
{
  TAO::Any_Dual_Impl_T<NenhumEventoCadastrado>::insert (
    _tao_any,
    NenhumEventoCadastrado::_tao_any_destructor,
    _tc_NenhumEventoCadastrado,
    _tao_elem);
}

/// Extraction to const pointer.
::CORBA::Boolean operator>>= (
  const ::CORBA::Any &_tao_any,
  const NenhumEventoCadastrado *&_tao_elem)
{
  return TAO::Any_Dual_Impl_T<NenhumEventoCadastrado>::extract (
    _tao_any,
    NenhumEventoCadastrado::_tao_any_destructor,
    _tc_NenhumEventoCadastrado,
    _tao_elem);
}
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_enum/any_op_cs.cpp:34


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

void operator<<= (
    ::CORBA::Any &_tao_any,
    Severidade _tao_elem)
{
  TAO::Any_Basic_Impl_T<Severidade>::insert (
      _tao_any,
      _tc_Severidade,
      _tao_elem);
}

::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    Severidade &_tao_elem)
{
  return
    TAO::Any_Basic_Impl_T<Severidade>::extract (
        _tao_any,
        _tc_Severidade,
        _tao_elem);
}
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/any_op_cs.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Logger>::to_object (
      ::CORBA::Object_ptr &_tao_elem) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {



/// Copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  Logger_ptr _tao_elem)
{
  Logger_ptr _tao_objptr =
    Logger::_duplicate (_tao_elem);
  _tao_any <<= std::addressof(_tao_objptr);
}

/// Non-copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  Logger_ptr *_tao_elem)
{
  TAO::Any_Impl_T<Logger>::insert (
    _tao_any,
    Logger::_tao_any_destructor,
    _tc_Logger,
    *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    Logger_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<Logger>::extract (
        _tao_any,
        Logger::_tao_any_destructor,
        _tc_Logger,
        _tao_elem);
}

}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_exception/cdr_op_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const NenhumEventoCadastrado &_tao_aggregate)
{
  // Marshal the repository ID.
  return (strm << _tao_aggregate._rep_id ());
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &,
    NenhumEventoCadastrado&)
{
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_enum/cdr_op_cs.cpp:29


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (TAO_OutputCDR &strm, Severidade _tao_enumerator)
{
  return strm << static_cast< ::CORBA::ULong> (_tao_enumerator);
}

::CORBA::Boolean operator>> (TAO_InputCDR &strm, Severidade & _tao_enumerator)
{
  ::CORBA::ULong _tao_temp = 0;
  ::CORBA::Boolean const _tao_success = strm >> _tao_temp;
  
  if (_tao_success)
    {
      _tao_enumerator = static_cast<Severidade> (_tao_temp);
    }
  
  return _tao_success;
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/cdr_op_cs.cpp:50


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Logger_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Logger_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  // Narrow to the right type.
  _tao_objref = TAO::Narrow_Utils< ::Logger>::unchecked_narrow (obj.in ());

  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



