//
// Interface Logger
//
//   T1 - Logger
//   Sistemas Distribuídos
//   Escola Politécnica - PUCPR
//   Prof. Luiz Lima Jr.
//   Alunos: Davi Natume, Eduardo Teodoro, Lucas Pelanda, Pedro Favero
//
// Compilar com:
//
//     tao_idl -Gstl Logger.idl
//
// para gerar stub e skeleton.
//

exception NenhumEventoCadastrado {};

enum Severidade {DEBUG, WARNING, ERROR, CRITICAL};

interface Logger {

    // métodos
    void log(in Severidade severidade, in string endereco, in short pid, in long hora, in string descricao);
    string locate(in Severidade s);
};
