// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1621

#include "LoggerI.h"
#include <iostream>

const std::string nomeSeveridade(::Severidade severidade)
{
  switch (severidade) {
    case DEBUG:
      return "DEBUG";
    case WARNING:
      return "WARNING";
    case ERROR:
      return "ERROR";
    case CRITICAL:
      return "CRITICAL";
    default:
      return "DESCONHECIDA";
  }
}

// Implementation skeleton constructor
Logger_i::Logger_i () {
}

// Implementation skeleton destructor
Logger_i::~Logger_i () {

}

void Logger_i::log (
  ::Severidade severidade,
  const std::string endereco,
  ::CORBA::Short pid,
  ::CORBA::Long hora,
  const std::string descricao)
{
  Log log(severidade, endereco, pid, hora, descricao);
  logs[severidade].push_back(log);

  std::cout << "Novo log registrado: " << std::endl;
  std::cout << "Severidade: " << nomeSeveridade(severidade) << std::endl;
  std::cout << "Endereco: " << endereco << std::endl;
  std::cout << "PID: " << pid << std::endl;
  std::cout << "Hora: " << hora << std::endl;
  std::cout << "Descricao: " << descricao << std::endl;
}

std::string Logger_i::locate (::Severidade s){
  if (logs[s].empty()){
    throw NenhumEventoCadastrado();
  }

  return logs[s].back().getEndereco();
}

