// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1567

#ifndef LOGGERI_PP8PTJ_H_
#define LOGGERI_PP8PTJ_H_

#include "LoggerS.h"

#include <vector>
#include <unordered_map>

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

class Log {
  private:
    ::Severidade severidade;
    std::string endereco;
    ::CORBA::Short pid;
    ::CORBA::Long hora;
    std::string descricao;
  
  public:
    Log(::Severidade severidade, const std::string endereco, ::CORBA::Short pid, ::CORBA::Long hora, const std::string descricao) : severidade(severidade), endereco(endereco), pid(pid), hora(hora), descricao(descricao) {}
    ::Severidade getSeveridade() { return severidade; }
    std::string getEndereco() { return endereco; }
    ::CORBA::Short getPid() { return pid; }
    ::CORBA::Long getHora() { return hora; }
    std::string getDescricao() { return descricao; }
};

class  Logger_i
  : public virtual POA_Logger
{
private:
  std::unordered_map<::Severidade, std::vector<Log>> logs;
public:
  // Constructor
  Logger_i ();

  // Destructor
  virtual ~Logger_i ();

  virtual
  void log (
    ::Severidade severidade,
    const std::string endereco,
    ::CORBA::Short pid,
    ::CORBA::Long hora,
    const std::string descricao);

  virtual
  std::string locate (
    ::Severidade s);
};


#endif /* LOGGERI_H_  */
